# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
image:
  file: Dockerfile.gitpod

tasks:
  - init: yarn install
    command: yarn serve

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 4200 for the frontend
    port: 4200
    onOpen: open-preview
# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
